name: Publish Python package to PyPI and TestPyPI

on:
  release:
    types: [published]

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@v5

      - name: Install build dependencies
        run: uv sync --dev

      - name: Build package
        run: uv run hatch build

      - name: Store distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-testpypi:
    name: Upload release to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for TestPyPI Trusted Publishing

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Upload release to PyPI (requires approval)
    needs: publish-testpypi
    runs-on: ubuntu-latest
    environment: # Define the environment for approval
      name: pypi
      url: https://pypi.org/p/l-command # Optional: Link to the PyPI project page
    permissions:
      id-token: write # Needed for PyPI Trusted Publishing

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # Publishes to PyPI by default
